### ISSUE TITLE
line 393: [: =: unary operator expected

### ISSUE THREAD

**Issue by gigaplus** [elhamdaoui/Odoo-install#5]
* Security Init File
./odoo_14_install.sh: line 360: CONTENT_NGINX: command not found
./odoo_14_install.sh: line 393: [: =: unary operator expected

**Comment by elhamdaoui** [comment]
Hi,
What operating system are you using?
The nginx content must be changed to work. Otherwise you can set INSTALL_NGINX = "False", then install nginx manually after that.


[see this commit](https://github.com/elhamdaoui/Odoo-install/commit/ee8541f8e5831677cd03049b9c6b5a4da752383c)

I will correct this later

**Comment by gigaplus** [comment]
I am running a virgin Ubuntu 20.04 and will use NGINX
Thank you for the **odoo_14_install.sh** commit January 12th.

Can you do the same commit on **odoo_15_install.sh** please

**Comment by elhamdaoui** [comment]
Done
